# Site settings
name: Guilherme Cunha
title: Guilherme Cunha | Developer
description: Desenvolvedor apaixonado por Programação, Inovação e Tecnologia.
url: https://guilhermecunha.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://guilhermecunha.github.io/img/og.png
logo: https://guilhermecunha.github.io/img/emojis/technologist.png
resume: https://guilhermecunha.github.io/resume.pdf
social:
  - title: email
    url: mailto:guiscunha@gmail.com
  - title: github
    url: https://github.com/GuilhermeCunha
  - title: linkedin
    url: https://www.linkedin.com/in/guilherme-cunha-a91123146/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
